### ISSUE TITLE
Issue: Creeper Explosion Exceeds Screen Limits

### ISSUE THREAD

**Issue by lucasbrasantos** [VillyRosa/creeper#2]
# Issue: Creeper Explosion Exceeds Screen Limits

## Description

Dear Minecraft Creeper Explosion development team,

I trust this message finds you well. Following the recent updates, I'd like to bring to your attention a new concern related to the Creeper's explosion animation.

### Observation:

The Creeper's explosion animation currently exceeds the screen limits, causing it to increase in size beyond the visible boundaries. This issue is particularly noticeable when the Creeper expands to explode, impacting the overall user experience.

#### Video Captures for Reference:

- **Desktop Screen Capture:**
[Desktop.webm](https://github.com/VillyRosa/creeper/assets/78361979/164df665-5efd-49d2-b6d9-12521ee8de22)

- **iPhone 12 Pro Screen Capture:**  
[Iphone12Pro.webm](https://github.com/VillyRosa/creeper/assets/78361979/21f2b9fd-41ed-4e4e-bed5-97b511aef994)

  
  
## Request:

I understand that the development team has been actively working on addressing various issues, and I appreciate the effort that has gone into resolving previous concerns. I kindly request your attention to investigate and rectify this matter to ensure a seamless and visually satisfying user experience.

If there is any additional information needed, or if further testing is required on my end, please do not hesitate to reach out.

Thank you for your ongoing commitment to improving the Minecraft Creeper Explosion site.

**Best regards,**

Lucas

**Comment by VillyRosa** [comment]
Dear Lucas,

Thank you for reaching out and providing feedback regarding the Creeper Explosion animation in Minecraft. We appreciate your diligence in bringing this matter to our attention.

After reviewing the video captures you provided, it appears that the Creeper Explosion animation is functioning as intended. The design philosophy behind the explosion animation involves it expanding beyond the screen boundaries to create a more immersive and dynamic experience for players.

The recent updates you mentioned were indeed aimed at addressing issues related to improper resizing, ensuring that the explosion retains its intended shape and proportions. We understand the importance of maintaining a visually satisfying user experience, and the adjustments made were intended to enhance the overall quality of the animation.

If you have any further concerns or if there are specific aspects you believe could be improved, please feel free to share additional details. We value player feedback, and your insights contribute to the ongoing refinement of creeper explosion.

Thank you for your understanding and continued support.

Best regards,

Villy
Minecraft Development Team
