### ISSUE TITLE
 Issue: Improve Website Performance based on Lighthouse Report

### ISSUE THREAD

**Issue by lucasbrasantos** [VillyRosa/creeper#3]
# Issue: Improve Website Performance based on Lighthouse Report

## Description

Dear Minecraft Creeper Explosion development team,

I hope this message finds you well. I recently conducted a performance analysis of the Minecraft Creeper Explosion site using Chrome DevTools Lighthouse. The results have highlighted several areas for improvement to enhance the overall user experience.

### Lighthouse Report:

- **Performance: 0**
- **Accessibility: 83**
- **Best Practices: 100**
- **SEO: 89**
- **PWA: - (Not Available)**

#### Diagnostics:

The Lighthouse report identified the following diagnostics that require attention:

- Minify CSS Error!
- Minify JavaScript Error!
- Serve images in next-gen formats Error!
- Enable text compression Error!
- Preconnect to required origins Error!
- Use HTTP/2 Error!
- Use video formats for animated content Error!
- Properly size images Error!
- Defer offscreen images Error!
- Reduce unused CSS Error!
- Reduce unused JavaScript Error!
- Efficiently encode images Error!
- Remove duplicate modules in JavaScript bundles Error!
- Avoid serving legacy JavaScript to modern browsers Error!

For more detailed information, you can access the Lighthouse tab in Chrome DevTools and initiate a report to analyze the website's performance.
---
### Screenshots for Reference:

1. ![Screenshot 1](https://github.com/VillyRosa/creeper/assets/78361979/6b5ebf00-a710-435d-b7f2-2ef85c77f1f0)
2. ![Screenshot 2](https://github.com/VillyRosa/creeper/assets/78361979/02433849-204b-4f35-90fd-a419dbf3a000)
3. ![Screenshot 3](https://github.com/VillyRosa/creeper/assets/78361979/40325720-c5fb-484a-9059-5a90c52450ae)
4. ![Screenshot 4](https://github.com/VillyRosa/creeper/assets/78361979/3730b421-23a9-4cb1-ab8a-72b0b4196ba3)
5. ![Screenshot 5](https://github.com/VillyRosa/creeper/assets/78361979/c71d1d55-49b4-452f-97a0-788fa15d0c56)
6. ![Screenshot 6](https://github.com/VillyRosa/creeper/assets/78361979/8d822e06-dfd6-4644-9b36-da13e6687cd9)
7. ![Screenshot 7](https://github.com/VillyRosa/creeper/assets/78361979/bb831b0d-e932-4cd9-8ce3-1dda99310ed5)

## Request:

I kindly request the development team's dedicated attention to address the performance-related issues highlighted in the Lighthouse report. Achieving a 100 score in each of the following areas will significantly contribute to providing a smoother and more efficient user experience.

If there is any additional information needed or if further testing is required on my end, please do not hesitate to reach out.

Thank you for your commitment to enhancing the Minecraft Creeper Explosion site.

**Best regards,**

Lucas

**Comment by VillyRosa** [comment]
Dear Lucas,

Thank you for taking the time to conduct a thorough performance analysis of the Minecraft Creeper Explosion website and providing valuable insights through the Lighthouse Report. We appreciate your dedication to ensuring a smooth user experience for our community.

After reviewing the report and the highlighted diagnostics, we want to address some aspects that are inherent to the nature of the Creeper Explosion website, which is a lightweight and open-source application:

Minify CSS, JavaScript, and Texts:
The Creeper Explosion website is designed to be a lightweight and open-source application. As such, we intentionally refrain from third-party minification of CSS, JavaScript, and texts directly on the live site. However, if you were to generate a production build, these optimization processes would be part of that pipeline.

Accessibility:
We are committed to ensuring the accessibility of our website. We have implemented semantic elements following best practices to make the Creeper Explosion site fully accessible. Additionally, some CSS classes may not be actively used from the start as they are intended for dynamic activation through JavaScript.

Please note that the Creeper Explosion site is continually evolving, and we appreciate your feedback in contributing to its improvement. If you have any further questions or suggestions, feel free to reach out.

Thank you for your understanding and support.

Best regards,

VillyRosa
Minecraft Development Team
